# netlify.toml
[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"          # <- adicionamos esta linha

# Configure redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
