# netlify.toml
[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Configure redirecionamentos para SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200